[package]
name = "bevy_split_canvas_example"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.3"
wasm-bindgen = "0.2.106"
bevy_split_canvas = { path = "..", version = "0.1.0" }

[lib]
crate-type = ["cdylib", "rlib"]